### PR TITLE
`expr_to_syntaxtree`: Quoted symbol fixes

### LINKED ISSUE #54: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Symbol
Standard libraries Mmap and Serialization both fail this way.  Atrocious provenance on this one!  

@topolarity describes this as our static eval of the first argument failing (`static_eval` in codegen.cpp returning null), which is where this error comes from.

```
julia> @activate JuliaLowering
julia> include("/your/path/to/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl")
ERROR: LoadError: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Symbol
Stacktrace:
  [1] macro expansion
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3 [inlined]
  [2] top-level scope
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3
  [3] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
  [4] eval(mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}}; expr_compat_mode::Bool)
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:358
  [5] kwcall(::@NamedTuple{expr_compat_mode::Bool}, ::typeof(Core.eval), mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}})
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:347
  [6] eval(mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}}; expr_compat_mode::Bool)
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:352
  [7] kwcall(::@NamedTuple{expr_compat_mode::Bool}, ::typeof(Core.eval), mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}})
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:347
  [8] top-level scope
    @ ~/JuliaLowering.jl/src/runtime.jl:182
  [9] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
 [10] eval_module(parentmod::Module, modname::String, expr_compat_mode::Bool, body::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}})
    @ JuliaLowering ~/JuliaLowering.jl/src/runtime.jl:180
 [11] top-level scope
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3
 [12] macro expansion
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3 [inlined]
 [13] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
 [14] eval(mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}}; expr_compat_mode::Bool)
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:358
 [15] kwcall(::@NamedTuple{expr_compat_mode::Bool}, ::typeof(Core.eval), mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}})
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:347
 [16] eval(mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}}; expr_compat_mode::Bool)
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:352
 [17] kwcall(::@NamedTuple{expr_compat_mode::Bool}, ::typeof(Core.eval), mod::Module, ex::SyntaxTree{SyntaxGraph{Dict{Symbol, Any}}})
    @ JuliaLowering ~/JuliaLowering.jl/src/eval.jl:347
 [18] top-level scope
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3
 [19] macro expansion
    @ ~/julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3 [inlined]
 [20] include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./Base.jl:309
 [21] top-level scope
    @ REPL[84]:1
in expression starting at julia/usr/share/julia/stdlib/v1.13/Mmap/src/Mmap.jl:3
```

### PR DESCRIPTION
**Pull request by mlechu**
Fix #54.  QuoteNode was previously converted to `(quote <contents>)` which lowers to a runtime call.  
- For plain symbol contents, this was too dynamic for ccall to handle, and optimizable in any case.  
- For Expr contents, I don't think using non-interpolating quote was correct in the first place.
- For LineNumberNode contents, we wrap with a QuoteNode on the way out, so we need to unwrap it on the way in.

I still need to think more about what the various forms of quoting mean when Expr and SyntaxTree are mixed, but this is at least an upgrade in number of passing tests.  I've added some cases from things I broke along the way.

Other fixes:
- Bool isa Integer, so prevent `expr_to_syntaxtree` from giving booleans `K"Integer"` kind
- enable logging of failures from `expr_to_syntaxtree` in the core lowering hook

### CODE REVIEW

File: test/compat.jl [hunk 1]
```diff
@@ -608,7 +608,24 @@ const JL = JuliaLowering
...
+        @test JuliaLowering.expr_to_syntaxtree(Expr(:toplevel, esc(LineNumberNode(1)))) ≈
+            @ast_ [K"toplevel"  [K"escape" "nothing"::K"core"]]
+        @test JuliaLowering.expr_to_syntaxtree(Expr(:toplevel, LineNumberNode(1))) ≈
+            @ast_ [K"toplevel" "nothing"::K"core"]
+        @test JuliaLowering.expr_to_syntaxtree(Expr(:toplevel, QuoteNode(LineNumberNode(1)))) ≈
+            @ast_ [K"toplevel" LineNumberNode(1)::K"Value"]
+        @test JuliaLowering.expr_to_syntaxtree(Expr(:call, :identity, LineNumberNode(1))) ≈
+            @ast_ [K"call" "identity"::K"Identifier" "nothing"::K"core"]
+        @test JuliaLowering.expr_to_syntaxtree(Expr(:call, :identity, QuoteNode(LineNumberNode(1)))) ≈
+            @ast_ [K"call" "identity"::K"Identifier" LineNumberNode(1)::K"Value"]
```
Comment (c42f) [inline test/compat.jl:628]: Haha aah LineNumberNode causing all sorts of issues.

Great test cases :+1:
